# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('global_components', '0003_headernav'),
        ('demo', '0002_auto_20180301_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='demopage',
            name='footer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='global_components.Footer'),
        ),
        migrations.AddField(
            model_name='demopage',
            name='header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='global_components.HeaderNav'),
        ),
        migrations.AlterField(
            model_name='demopage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('full_width_feature', wagtail.wagtailcore.blocks.StructBlock((('headline', wagtail.wagtailcore.blocks.CharBlock(help_text='Add a headline for the feature.', max_length=255, required=False)), ('paragraph', wagtail.wagtailcore.blocks.TextBlock(help_text='Add a paragraph with the feature content.', required=False)), ('cta', wagtail.wagtailcore.blocks.StructBlock((('display_text', wagtail.wagtailcore.blocks.CharBlock(default='', label='Please input the display text here.')), ('url', wagtail.wagtailcore.blocks.URLBlock())))), ('background_image', wagtail.wagtailimages.blocks.ImageChooserBlock(help_text='Add a background image for this feature.', required=False))))),)),
        ),
    ]
