# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_title', models.CharField(help_text='Add a short description for this footer.', max_length=255)),
                ('footer_items', wagtail.core.fields.StreamField((('entry', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock((('icon', wagtail.images.blocks.ImageChooserBlock(required=True)), ('url', wagtail.core.blocks.URLBlock(required=True))), label='Footer Entry'))),))),
            ],
        ),
    ]
