# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('global_components', '0002_auto_20180215_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderNav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('menu_items', wagtail.wagtailcore.fields.StreamField((('external_link', wagtail.wagtailcore.blocks.StructBlock((('display_text', wagtail.wagtailcore.blocks.CharBlock(default='', label='Please input the display text here.')), ('url', wagtail.wagtailcore.blocks.URLBlock()), ('submenus', wagtail.wagtailcore.blocks.StreamBlock((('external_link', wagtail.wagtailcore.blocks.StructBlock((('display_text', wagtail.wagtailcore.blocks.CharBlock(default='', label='Please input the display text here.')), ('url', wagtail.wagtailcore.blocks.URLBlock())))), ('page_link', wagtail.wagtailcore.blocks.StructBlock((('display_text', wagtail.wagtailcore.blocks.CharBlock(default='', label='Please input the display text here.')), ('page', wagtail.wagtailcore.blocks.PageChooserBlock())))))))))), ('page_link', wagtail.wagtailcore.blocks.StructBlock((('display_text', wagtail.wagtailcore.blocks.CharBlock(default='', label='Please input the display text here.')), ('page', wagtail.wagtailcore.blocks.PageChooserBlock()), ('submenus', wagtail.wagtailcore.blocks.StreamBlock((('external_link', wagtail.wagtailcore.blocks.StructBlock((('display_text', wagtail.wagtailcore.blocks.CharBlock(default='', label='Please input the display text here.')), ('url', wagtail.wagtailcore.blocks.URLBlock())))), ('page_link', wagtail.wagtailcore.blocks.StructBlock((('display_text', wagtail.wagtailcore.blocks.CharBlock(default='', label='Please input the display text here.')), ('page', wagtail.wagtailcore.blocks.PageChooserBlock()))))))))))))),
            ],
        ),
    ]
